namePrefix: dev-
nameSuffix: "-001"

resources:
- service.yml
- deployment.yml

patches:
- path: increase_replicas.yml
- path: set_memory.yml

images:
- name: nginx
  newName: my.image.registry/nginx
  newTag: "1.4.0"

replacements:
- source:
    kind: Deployment
    name: my-nginx
    fieldPath: metadata.name
  targets:
  - select:
      kind: Deployment
      name: my-nginx
    fieldPaths:
    - spec.template.spec.containers.0.command.2

